#!/usr/bin/env node
/**
 * tools/install-desktop.mjs — put a "Jve Studio" icon on the real Desktop.
 *
 *   node tools/install-desktop.mjs                  # create the launcher icon
 *   node tools/install-desktop.mjs --autostart      # + start the host at logon (hidden)
 *   node tools/install-desktop.mjs --remove         # take both back out
 *
 * Why this exists: the compaction host is a Node server that would otherwise die with
 * the agent window that spawned it. The launcher starts it DETACHED (survives closing
 * the terminal or the agent app) and opens http://127.0.0.1:50505/ in your browser.
 * Double-clicking the icon again is safe: the server probes the canonical port first
 * and a second copy exits quietly, so the icon never forks a duplicate on the port.
 *
 * Windows notes (learned the hard way):
 *  – the real Desktop can be OneDrive-redirected, so the folder is resolved through
 *    the shell API ([Environment]::GetFolderPath('Desktop')), not %USERPROFILE%\Desktop.
 *  – the log is written nothing to the terminal of the double-clicked window: the
 *    server runs hidden (Start-Process -WindowStyle Hidden); the browser is the UI.
 *  – --autostart drops a VBS stub in the Startup folder that runs the same hidden
 *    command at logon, so the host is up before you even think about compaction.
 *
 * Privacy: nothing personal is written anywhere in the distribution. The generated
 * launcher contains only machine-local paths (node binary, this checkout) computed
 * at install time; it is written to YOUR desktop, never into the repository.
 */
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, "..");
const STUDIO_APP = path.resolve(ROOT, "lib", "jve-studio-app.mjs");
const NODE_BIN = process.execPath;
const HOST = "127.0.0.1";
const PORT = 50505;
const URL = `http://${HOST}:${PORT}/`;
const LAUNCHER_NAME = "Jve Studio";

const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);

function ps(script) {
  const r = spawnSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], { encoding: "utf8", timeout: 15_000 });
  return (r.stdout ?? "").trim();
}

/* ------------------------------------------------------------- desktop folder */
function desktopDir() {
  // test/CI knob: JVC_DESKTOP_DIR redirects where the icon is written (default: the real Desktop)
  if (process.env.JVC_DESKTOP_DIR) return process.env.JVC_DESKTOP_DIR;
  if (process.platform === "win32") {
    try {
      const out = ps("[Environment]::GetFolderPath([Environment+SpecialFolder]::Desktop)");
      if (out && fs.existsSync(out)) return out;
    } catch { /* fall through */ }
  }
  return path.join(os.homedir(), "Desktop");
}
function startupDir() {
  if (process.platform !== "win32") return null;
  // test/CI knob: JVC_STARTUP_DIR redirects the logon stub location (keeps dry runs off the real Startup folder)
  if (process.env.JVC_STARTUP_DIR) return process.env.JVC_STARTUP_DIR;
  return path.join(process.env.APPDATA ?? path.join(os.homedir(), "AppData", "Roaming"), "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
}

/* ------------------------------------------------------------------ artefacts */
// PS single-quote literal: embedded ' is doubled. Built then base64'd as UTF-16LE and
// handed to powershell -EncodedCommand — immune to the cmd→PS quoting gauntlet, so paths
// with spaces (node.exe under "C:\Program Files\…") survive intact.
const psq = (s) => `'${String(s).replace(/'/g, "''")}'`;
function batContent() {
  const script = `Start-Process -FilePath ${psq(NODE_BIN)} -ArgumentList ${psq(`"${STUDIO_APP}" --no-browser`)} -WindowStyle Hidden`;
  const enc = Buffer.from(script, "utf16le").toString("base64");
  return [
    "@echo off",
    "rem Jve Studio — JevCompact local compaction host (generated by tools/install-desktop.mjs)",
    "setlocal",
    `curl -s -f -o nul ${URL} && (start "" "${URL}" & exit /b 0)`,
    `powershell -NoProfile -EncodedCommand ${enc}`,
    "timeout /t 3 /nobreak >nul",
    `start "" "${URL}"`,
    "endlocal",
    "",
  ].join("\r\n");
}
function vbsContent() {
  return [
    "' Jve Studio autostart (generated by tools/install-desktop.mjs)",
    "Set sh = CreateObject(\"WScript.Shell\")",
    `sh.Run """${NODE_BIN}"" ""${STUDIO_APP}"" --no-browser", 0, False`,
    "",
  ].join("\r\n");
}
function desktopEntryContent() {
  // Linux .desktop — runs the host in a terminal window; browser opens itself
  return [
    "[Desktop Entry]",
    "Type=Application",
    "Version=1.0",
    "Name=Jve Studio",
    "Comment=JevCompact local compaction host",
    "Categories=Development;",
    "Terminal=true",
    `Exec="${NODE_BIN}" "${STUDIO_APP}"`,
    "Icon=utilities-terminal",
    "StartupNotify=true",
    "",
  ].join("\n");
}
function macCommandContent() {
  return ["#!/bin/sh", `exec "${NODE_BIN}" "${STUDIO_APP}"`, ""].join("\n");
}

/* ---------------------------------------------------------------------- write */
const targets = [];
if (process.platform === "win32") {
  targets.push({ file: path.join(desktopDir(), `${LAUNCHER_NAME}.bat`), content: batContent(), label: "desktop launcher (.bat)" });
  if (has("--autostart")) targets.push({ file: path.join(startupDir() ?? desktopDir(), "JveStudio-Autostart.vbs"), content: vbsContent(), label: "logon autostart (VBS)" });
} else if (process.platform === "linux") {
  targets.push({ file: path.join(desktopDir(), "jve-studio.desktop"), content: desktopEntryContent(), label: "desktop entry", mode: 0o755 });
  if (has("--autostart")) targets.push({ file: path.join(os.homedir(), ".config", "autostart", "jve-studio.desktop"), content: desktopEntryContent(), label: "session autostart" });
} else {
  targets.push({ file: path.join(desktopDir(), `${LAUNCHER_NAME}.command`), content: macCommandContent(), label: "double-clickable command", mode: 0o755 });
  if (has("--autostart")) console.log("(macOS: add the .command to System Settings ▸ Login Items manually — the icon alone still works)");
}

if (has("--remove")) {
  for (const f of [path.join(desktopDir(), `${LAUNCHER_NAME}.bat`), path.join(desktopDir(), "jve-studio.desktop"), path.join(desktopDir(), `${LAUNCHER_NAME}.command`), path.join(startupDir() ?? "/", "JveStudio-Autostart.vbs"), path.join(os.homedir(), ".config", "autostart", "jve-studio.desktop")]) {
    try { fs.rmSync(f); console.log(`removed ${f}`); } catch { /* never existed */ }
  }
  process.exit(0);
}

if (!fs.existsSync(STUDIO_APP)) { console.error(`studio app not found at ${STUDIO_APP}`); process.exit(1); }
for (const t of targets) {
  fs.mkdirSync(path.dirname(t.file), { recursive: true });
  fs.writeFileSync(t.file, t.content, "utf8");
  if (t.mode) fs.chmodSync(t.file, t.mode);
  console.log(`installed ${t.label.padEnd(28)} → ${t.file}`);
}
console.log("");
console.log("Double-click the Jve Studio icon: the host starts detached (it survives");
console.log(`closing the terminal / the agent app) and your browser opens ${URL}`);
console.log("Pick a harness, press Sync, then Dry run before any Compact. Restore replays");
console.log("the newest pre-compaction backup — see docs/GUIDE.md (pictorial quick start).");
